# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test & Analyze
      uses: highbyte/sonarscan-dotnet@v2.1.3
      with:
        sonarProjectKey: ${{ secrets.SONAR_PROJECTKEY }}
        sonarProjectName: ${{ secrets.SONAR_PROJECTNAME }}
        sonarOrganization: ${{ secrets.SONAR_ORGANIZATION }}
        dotnetTestArguments: --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"

env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
