# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Download a Build Artifact
      uses: actions/download-artifact@v5.0.0
      with: 
        # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
        name: test # optional
          # IDs of the artifacts to download, comma-separated. Either inputs `artifact-ids` or `name` can be used, but not both.

                    
